### ISSUE TITLE
Add sounds that correspond to the vibrations

### ISSUE THREAD

**Issue by jbphet** [phetsims/quake#13]
In the 4/5/2022 haptics meeting, the quad and haptics design teams discussed whether support for sounds that correspond to the vibrations should be added.  It was decided that yes, this feature should be added.

**Comment by jbphet** [comment]
We reviewed an early prototype of this functionality at todays haptics+quad meeting, and got some feedback that we should probably mellow the vibration sound a little bit from what we are currently using.  @Ashton-Morris will take a shot at this.

**Comment by Ashton-Morris** [comment]
@jbphet I am adding 5 options to test out. If you want to do only three, my favorites are haptic-buzz-loop-v2, haptic-buzz-loop-v2-001, and haptic-buzz-loop-v2-003. [They are stored here. ](https://drive.google.com/drive/folders/1MvoFmyoQidly_EzJKfLNSCrA-_S88-JN?usp=sharing)

- haptic-buzz-loop-v2.wav
- haptic-buzz-loop-v2-001.wav
- haptic-buzz-loop-v2-002.wav
- haptic-buzz-loop-v2-003.wav
- haptic-buzz-loop-v2-004.wav
- haptic-buzz-loop-v2.mp3
- haptic-buzz-loop-v2-001.mp3
- haptic-buzz-loop-v2-002.mp3
- haptic-buzz-loop-v2-003.mp3
- haptic-buzz-loop-v2-004.mp3

**Comment by jbphet** [comment]
I just sent this to @Ashton-Morris over Slack:

> I listened to the new sounds that were added for https://github.com/phetsims/quake/issues/13, and I feel like they are okay but most are a little too "buzzy", since we were looking for something a bit more mellow sounding.  I'll try a couple of them, but would it be possible to also get a sound like a slightly overdriven B3 in there too, maybe a single low-ish note or a root and fifth sort of thing?  Thanks.

**Comment by Ashton-Morris** [comment]
Added two Organ-ish Options 

- haptic-buzz-loop-v2-007.wav
- haptic-buzz-loop-v2-006.mp3
- haptic-buzz-loop-v2-006.wav
- haptic-buzz-loop-v2-007.mp3

> I just sent this to @Ashton-Morris over Slack:
> 
> > I listened to the new sounds that were added for #13, and I feel like they are okay but most are a little too "buzzy", since we were looking for something a bit more mellow sounding.  I'll try a couple of them, but would it be possible to also get a sound like a slightly overdriven B3 in there too, maybe a single low-ish note or a root and fifth sort of thing?  Thanks.

**Comment by jbphet** [comment]
We reviewed a number of these sounds with the design team today and decided on the low organ note sound, which is the file named `haptic-buzz-loop-v2-006`.  I'll integrate this one.

**Comment by jbphet** [comment]
We are pretty close to being done with this, but when testing on Jesse's phone we noticed a clicking sound at the end of the vibration sounds in some cases, and I can sometimes here it on my Samsung tablet too.  I'll take a bit of time and see if I can make it go away.

**Comment by jbphet** [comment]
This is done, and was released in version 0.1.0.  Closing.
