### ISSUE TITLE
Privacy policy needed to publish app to Play Store

### ISSUE THREAD

**Issue by jbphet** [phetsims/quake#25]
I'm working through the steps to publish this to the Play Store (see parent issue #22), and I'm being told by the Play Store Console that I need to link to a privacy policy.  I could probably post this on GitHub, but I have little idea of what it is supposed to contain.

@mattpen - Where did you get the privacy policy for the PhET app and where is it hosted?

**Comment by mattpen** [comment]
@jbphet - We just provide a link to our privacy policy: https://phet.colorado.edu/en/android-app-privacy-policy. 

@oliver-phet - Do you know if we can just reuse this for quake?

**Comment by oliver-phet** [comment]
@jbphet I assume we aren't collecting any analytics in quake? I don't think we should reuse the Android policy for quake since it states 

> This Privacy Policy applies to your use of the PhET Simulations Android app, and only the Android app.

It may just be time to create a derivative policy for quake? Assuming we aren't collecting any analytics, it could be a simple policy.

**Comment by oliver-phet** [comment]
PhET Interactive Simulations and University of Colorado Boulder (“the CU PhET team”, “we”, or “us”) are deeply committed to protecting your privacy and creating a safe and secure environment for learners of all ages. This Privacy Policy applies to your use of the PhET Simulations Quake app, and only the Quake app. For information about use of PhET simulations and related resources on the PhET website, visit the PhET website.

In connection with your use of the PhET Simulations Android app, NO personally identifiable information is collected by the CU PhET team. The PhET Simulations Quake app is meant to provide [fill in]. As we strive to collect the minimum amount of information needed to advance our educational mission, we have determined that there is no need for the collection of personal data within this app.

Some standard aggregated data (e.g. sales, sessions, crashes) related to the PhET Simulations Quake app is provided to app developers through Google’s Play Console. However, we have NO access to any personally-identifiable information through this service.

If you have questions about this privacy policy, you may submit a written inquiry to [privacy@cu.edu](mailto:privacy@cu.edu).

**Comment by jbphet** [comment]
@oliver-phet - That sounds great, thanks.  I'll replace "Quake" with "Haptics Playground", and set it up.

**Comment by jbphet** [comment]
I took the blurb that @oliver-phet added above, edited it as needed, and added it as a markdown document to this repo.  I used a link to it in the Play Store console to set the privacy policy, but I'm wondering if we can post something a bit more official looking on the website.  @mattpen - Is there a way I could do that, either with the current markdown doc or a basic HTML file?

**Comment by mattpen** [comment]
I added the policy to the website doc root: https://phet.colorado.edu/haptics-playground-privacy-policy.html

I tried to add the html file to the quake repo, but it failed because I don't have git hooks setup yet:

```
[~/phet/git/quake/doc]$ git commit -am "added privacy policy html https://github.com/phetsims/quake/issues/25"
node:internal/modules/cjs/loader:988
  throw err;
  ^

Error: Cannot find module '/Users/matt/phet/git/perennial/js/scripts/hook-pre-commit.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Module._load (node:internal/modules/cjs/loader:833:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.10.0
```

**Comment by jbphet** [comment]
Thanks @mattpen.  I just updated the link using the Play Store Console to point to the one that @mattpen posted on the website (https://phet.colorado.edu/haptics-playground-privacy-policy.html), and I think we should be good to go on this.  Closing.
