### ISSUE TITLE
Create tablet screenshot for Play Store listing

### ISSUE THREAD

**Issue by jbphet** [phetsims/quake#30]
@KatieWoe - The Play Store listing could use a screenshot from a tablet, and I recently gave my test device to you.  Could you please use it to create a screenshot of the app and attach it to this issue?  Please choose a screen and a situation that you feel looks fairly decent.  Once done, assign the issue back to me and I'll upload it through the Play Store Console.

**Comment by KatieWoe** [comment]
How does this look? I cropped the top and bottom, and I'm not sure if there are dimension requirements, so let me know if something needs to be changed.
![Screenshot_20221122_091328_HapticsPlaygroundcrop](https://user-images.githubusercontent.com/41024075/203367728-de605b4b-edea-4a25-aa3b-ee0f7bf45e81.jpg)

**Comment by jbphet** [comment]
I just uploaded it via the Play Store console, and it seemed to be accepted, so I think we're good.  Thanks @KatieWoe.  Closing.
