### ISSUE TITLE
Create artwork for the main screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/quake#5]
I grabbed an open-source piece of artwork of a playground off the web and did some resizing to make it look half decent on the main screen for the Haptics Playground app.  It currently looks like this in an Android emulator:

![image](https://user-images.githubusercontent.com/3082831/148140149-c5d6a1a9-7b01-48f0-a0b6-2ee0e78d7875.png)

I was talking with @Ashton-Morris during our weekly sound+haptics meeting, and he thought he might be able to create something that is a bit wider and less tall that would look better.  Plus, if he did this, we would own it, so we wouldn't have to worry about any licensing issues.

The current image is 170 pixels wide by 200 pixels high.  Let's start with something that is roughly the reverse of that, i.e. 200 x 170, and we will see how that works.  Also, if there is any way to tie in the concept of vibration, that would be great.

@Ashton-Morris - This is pretty open ended, so take a look at the context in the image above, the dimensions specified, consider the themes of "playground" and "vibration", and see what you can come up with.

**Comment by jbphet** [comment]
Just had a thought: It would be great if the artwork incorporated the PhET logo somehow.

**Comment by Ashton-Morris** [comment]
@jbphet I have some art for this.
[Here it is](https://drive.google.com/file/d/1uWBMMetLc-3dAdOScNE9IuGvgyfBr5r3/view?usp=sharing)

**Comment by Ashton-Morris** [comment]
Let me know if you want me to adjust the sizing.

**Comment by jbphet** [comment]
@Ashton-Morris and I reviewed this in today's weekly meeting, and here are some suggested next steps:

- [x] Make the "Haptics Playground" words more visible and the logo less, and use the standard colors for the logo.  Maybe use "by PhET", so that it's kind of a byline.
- [x] The current aspect ratio is 3.8 (width to height).  It would be nice to reduce the height a bit and thereby gain some more space on the screen, so perhaps reduce it such that the aspect ratio goes to 4:1.
- [x] The perspective on the slide seems a little off, it would be nice to fix it up a bit
- [x] Get a vector art version of the logo, or fix up the parts of the imported version that don't seem to have "vectored" quite right

**Comment by Ashton-Morris** [comment]
I am uploading some options [here](https://drive.google.com/drive/folders/16bKIpUDANSkrY9x2RZLu6-SvAMdzPG70?usp=sharing). It has different Font logo colors and border options. 

Playground-Art-for-Haptics-Playground-v6b.png
Playground-Art-for-Haptics-Playground-v6a.png
Playground-Art-for-Haptics-Playground-v6.png
Playground-Art-for-Haptics-Playground-v5b.png
Playground-Art-for-Haptics-Playground-v5a.png
Playground-Art-for-Haptics-Playground-v5.png
Playground-Art-for-Haptics-Playground-v4b.png
Playground-Art-for-Haptics-Playground-v4a.png
Playground-Art-for-Haptics-Playground-v4.png
Playground-Art-for-Haptics-Playground-v3b.png
Playground-Art-for-Haptics-Playground-v3a.png
Playground-Art-for-Haptics-Playground-v3.png
Playground-Art-for-Haptics-Playground-v1b.png
Playground-Art-for-Haptics-Playground-v1a.png
Playground-Art-for-Haptics-Playground-v1.png
Playground-Art-for-Haptics-Playground-v2.png
Playground-Art-for-Haptics-Playground-v2a.png
Playground-Art-for-Haptics-Playground-v2b.png

**Comment by jbphet** [comment]
@Ashton-Morris and I reviewed this in today's review meeting.  The two preferred versions at this point are v1b and v6b.  There are a few mods that we'd like to try to these:

- Thicker letters, perhaps a bold font weight
- A slightly thicker stroke on the letters
- Possibly moving or removing the trees that are behind the upper portions of the words so that there is less visual interference with the letters

**Comment by Ashton-Morris** [comment]
I have added some iterations.

- Playground-Art-for-Haptics-Playground-Bolder-v1b.png
- Playground-Art-for-Haptics-Playground-Bolder-v1b.2.png
- Playground-Art-for-Haptics-Playground-Bolder-v6b.2.png
- Playground-Art-for-Haptics-Playground-Bolder-v6b.png

**Comment by jbphet** [comment]
I integrated a couple of these this week, and we are currently thinking that the v6b.2 version looks the best.  One last request: Can we remove or soften some of the wavy lines on the playground, and in particular the one under the title?

**Comment by Ashton-Morris** [comment]
Added some updates to that art.

- Playground-Art-for-Haptics-Playground-Bolder-v6b.2.2.png
- Playground-Art-for-Haptics-Playground-Bolder-v6b.2.1.png

**Comment by jbphet** [comment]
I think v6b.2.1 looks great, and I think we should go with that one.  Below is a screenshot of what it looks like in context.  Thanks @Ashton-Morris!  Closing.

![image](https://user-images.githubusercontent.com/3082831/154331653-5212ad3b-2a97-4e0b-a322-42eef982d56c.png)
