### ISSUE TITLE
Add a sound that corresponds to a quick vibratory jolt

### ISSUE THREAD

**Issue by jbphet** [phetsims/quake#7]
In #6, some sounds were created that could be played along with the haptics vibrations, or instead of them on platforms where no vibration support is available.  We could probably use one additional sound, one that can be played when the vibration is just a  quick jolt or bump.  This could be a one-shot sort of sound instead of the loop that was used for the other sounds.

**Comment by Ashton-Morris** [comment]
[Here is your sound](https://drive.google.com/file/d/1dHKt7e5wwVFWvJ-Q5BjF3rcSZhBrP0Hp/view?usp=sharing)

**Comment by jbphet** [comment]
At least for now, we're not going to use this sound.  It turns out that the tablet doesn't actually support jolts, it just supports shorter buzzes, so I'm using the sound associated with that instead.  Closing.
