### ISSUE TITLE
Icon artwork for the nav bar

### ISSUE THREAD

**Issue by jbphet** [phetsims/quake#8]
The current mockups for the Haptics Playground design are using some pretty crude, mouse-drawn icons for the "Clicks", "Buzzes", and "Patterns" selections on the nav bar (see image below).  Since this design has been approved by the design team, it's probably time to create "real" icon artwork for these.

Note that we only need the icons, not the words - the words can be added programmatically.

@Ashton-Morris said he'd take this on, so I'll assign to him.

![image](https://user-images.githubusercontent.com/3082831/152047080-486593bb-5474-45e0-9e7b-77e7f2dae959.png)

**Comment by Ashton-Morris** [comment]
I have some art to test out[ located here](https://drive.google.com/drive/folders/16bKIpUDANSkrY9x2RZLu6-SvAMdzPG70?usp=sharing).

- Haptics-Playground-Clicks-2.png
- Haptics-Playground-Patterns.png
- Haptics-Playground-Buzzes.png
- Haptics-Playground-Clicks.png

**Comment by jbphet** [comment]
@Ashton-Morris - I took a quick look, and the clicks and buzzes ones look good.  I don't think the one for patterns is quite what we're after.  The idea for this one is that it is a combination of sine waves and spaces, rather than a more complex looking waveform.

**Comment by Ashton-Morris** [comment]
@jbphet [How about something like this?](https://drive.google.com/file/d/1fJR43Ro0PVhdiZxLVkGw72hSZAzjloqW/view?usp=sharing)

**Comment by jbphet** [comment]
I tried these out, and at the moment it looks like this:

![image](https://user-images.githubusercontent.com/3082831/153067686-053b8eac-b3d1-47cf-8ef3-17f57792cd94.png)

Here are a few things I think we should try:

- The click should be about half as wide
- The buzz frequency should be about twice as much as it is (or half as much distance between each cycle)
- The "pattern" icon should have a couple of cycles of the frequency used for the other icons, then stillness (in the middle in the y direction), then a couple more cycles

**Comment by Ashton-Morris** [comment]
Adding some icons.

- Haptics-Playground-Buzzes-v3.png
- Haptics-Playground-Patterns-v3a.png
- Haptics-Playground-Patterns-v3.png
- Haptics-Playground-Clicks-v3a.png
- Haptics-Playground-Clicks-v3.png
- Haptics-Playground-Buzzes-v3a.png

**Comment by jbphet** [comment]
These look good.  I ended up using the v3 versions with the thicker stroke instead of the v3a versions.  Here's a screenshot with the latest ones integrated:

![image](https://user-images.githubusercontent.com/3082831/155037559-95dad29e-cfd1-42ee-900d-41cf99456ae8.png)

**Comment by jbphet** [comment]
I think we're good on this, at least for now.  Closing.

**Comment by jbphet** [comment]
I'd like to try a lighter colored nav bar that draws from the header artwork.  @Ashton-Morris - As we discussed in today's meeting, can I get black and SVG versions of the click, buzzes, and patterns artwork?

**Comment by Ashton-Morris** [comment]
I have added the below files to the Art folder.

- Haptics-Playground-Patterns-v3.svg
- Haptics-Playground-Buzzes-v3.svg
- Haptics-Playground-Clicks-v3.svg
- Haptics-Playground-Patterns-v3-Black.png
- Haptics-Playground-Buzzes-v3-Black.png
- Haptics-Playground-Clicks-v3-Black.png

**Comment by jbphet** [comment]
I experimented with the the darker artwork, and have decided to leave things as they are, at least for now.  Closing.
